import { describe, expect, it } from 'vitest';
import { resolveP15ElementorContainerLinearGradients, serializeP15ElementorContainerLinearGradientSummary, P15_ELEMENTOR_CONTAINER_LINEAR_GRADIENT_MANIFEST_VERSION } from '../src/targets/elementor/container-linear-gradient-composition';
import { P15_NEUTRAL_EXPORT_IR_VERSION, type P15NeutralExportDocumentV1 } from '../src/targets/elementor/neutral-export-ir';
import { fingerprintP15NeutralExportDocument } from '../src/targets/elementor/neutral-export-ir-identity';
import { buildElementorTemplateCandidateIdentity } from '../src/targets/elementor/import-validation-contract';
import { generateElementorV3TemplateCandidate } from '../src/targets/elementor/v3-template-generator';
function source(): P15NeutralExportDocumentV1 { return { schemaVersion:1, irVersion:P15_NEUTRAL_EXPORT_IR_VERSION, title:'PRIVATE', documentType:'section', nodes:[{kind:'container',sourceNodeId:'root',direction:'column',children:[{kind:'container',sourceNodeId:'nested',direction:'row',children:[]}]}]}; }
function manifest(s: P15NeutralExportDocumentV1) { const g=generateElementorV3TemplateCandidate(s); if(!g.candidate) throw Error(); const common={schemaVersion:1 as const,manifestVersion:P15_ELEMENTOR_CONTAINER_LINEAR_GRADIENT_MANIFEST_VERSION,sourceIrFingerprint:fingerprintP15NeutralExportDocument(s),baseCandidateIdentityDigest:buildElementorTemplateCandidateIdentity(g.candidate).digest,gradientInferencePerformed:false as const,responsiveInferencePerformed:false as const,figmaMutation:false as const,networkAccess:false as const,responsiveClosureClaim:false as const,targetCompatibilityClaim:false as const,productionAcceptance:false as const,downloadEnabled:false as const}; return {...common,containers:[{sourceNodeId:'root',normal:{colorA:'#112233',colorB:'#aabbcc',stopA:0,stopB:100,angleDeg:180,tabletStopA:10,mobileAngleDeg:90},hover:{colorA:'#334455',colorB:'#ddeeff',stopA:20,stopB:80,angleDeg:90}},{sourceNodeId:'nested',hover:{colorA:'#010203',colorB:'#fefefe',stopA:5,stopB:95}}]}; }
describe('P15 Container linear gradients',()=>{ it('resolves explicit normal and hover gradients with breakpoint isolation',()=>{const s=source();const r=resolveP15ElementorContainerLinearGradients(s,manifest(s));expect(r.status).toBe('RESOLVED');expect(r.resolvedGradients).toHaveLength(2);const root=r.template?.content[0];const nested=root?.elements[0];expect(root?.settings).toMatchObject({background_background:'gradient',background_gradient_type:'linear',background_gradient_angle:{size:180,unit:'deg'},background_color_stop_tablet:10,background_gradient_angle_mobile:{size:90,unit:'deg'}});expect(root?.settings).toMatchObject({background_hover_background:'gradient',background_hover_gradient_angle:{size:90,unit:'deg'}});expect(nested?.settings).toMatchObject({background_hover_background:'gradient'});expect(serializeP15ElementorContainerLinearGradientSummary(r)).not.toContain('PRIVATE');}); it('rejects invalid ranges, duplicate ids, stale identity, unknown fields, authority inflation and conflicts',()=>{const s=source();const v=manifest(s);for(const bad of [{...v,productionAcceptance:true},{...v,baseCandidateIdentityDigest:'sha256:'+'0'.repeat(64)},{...v,containers:[{...v.containers[0],normal:{...v.containers[0]!.normal!,stopA:101}}]},{...v,containers:[v.containers[0],v.containers[0]]},{...v,containers:[{...v.containers[0],extra:'x'}]}])expect(resolveP15ElementorContainerLinearGradients(s,bad).status).toBe('REJECTED');const conflict={...v,containers:[{...v.containers[0],normal:{...v.containers[0]!.normal!,colorA:'#ffffff'}}]};const s2={...s,nodes:[{...s.nodes[0],backgroundColorHex:'#123456'}]};expect(resolveP15ElementorContainerLinearGradients(s2,conflict).status).toBe('REJECTED');}); });
