import { describe, expect, it } from 'vitest';
import { resolveP15ElementorContainerHoverTransitions, serializeP15ElementorContainerHoverTransitionSummary, P15_ELEMENTOR_CONTAINER_HOVER_TRANSITION_MANIFEST_VERSION } from '../src/targets/elementor/container-hover-transition-composition';
import { P15_NEUTRAL_EXPORT_IR_VERSION, type P15NeutralExportDocumentV1 } from '../src/targets/elementor/neutral-export-ir';
import { fingerprintP15NeutralExportDocument } from '../src/targets/elementor/neutral-export-ir-identity';
import { buildElementorTemplateCandidateIdentity } from '../src/targets/elementor/import-validation-contract';
import { generateElementorV3TemplateCandidate } from '../src/targets/elementor/v3-template-generator';
function source(): P15NeutralExportDocumentV1 { return {schemaVersion:1,irVersion:P15_NEUTRAL_EXPORT_IR_VERSION,title:'PRIVATE',documentType:'section',nodes:[{kind:'container',sourceNodeId:'root',direction:'column',children:[{kind:'container',sourceNodeId:'nested',direction:'row',children:[]}]}]}; }
function manifest(s:P15NeutralExportDocumentV1){const g=generateElementorV3TemplateCandidate(s);if(!g.candidate)throw Error();return {schemaVersion:1 as const,manifestVersion:P15_ELEMENTOR_CONTAINER_HOVER_TRANSITION_MANIFEST_VERSION,sourceIrFingerprint:fingerprintP15NeutralExportDocument(s),baseCandidateIdentityDigest:buildElementorTemplateCandidateIdentity(g.candidate).digest,containers:[{sourceNodeId:'root',backgroundHover:0,overlayHover:1.5,borderHover:3},{sourceNodeId:'nested',backgroundHover:0.1}],transitionInferencePerformed:false as const,responsiveInferencePerformed:false as const,figmaMutation:false as const,networkAccess:false as const,responsiveClosureClaim:false as const,targetCompatibilityClaim:false as const,productionAcceptance:false as const,downloadEnabled:false as const};}
describe('P15 Container hover transitions',()=>{it('resolves all three exact transition families with bounded seconds',()=>{const s=source();const r=resolveP15ElementorContainerHoverTransitions(s,manifest(s));expect(r.status).toBe('RESOLVED');expect(r.resolvedTransitions).toHaveLength(2);expect(r.template?.content[0]?.settings).toMatchObject({background_hover_transition:{size:0,unit:'s'},background_overlay_hover_transition:{size:1.5,unit:'s'},border_hover_transition:{size:3,unit:'s'}});expect(serializeP15ElementorContainerHoverTransitionSummary(r)).not.toContain('PRIVATE');});it('rejects non-step ranges, duplicate/stale/extra/conflicting and authority-inflated manifests',()=>{const s=source();const v=manifest(s);for(const bad of [{...v,productionAcceptance:true},{...v,baseCandidateIdentityDigest:'sha256:'+'0'.repeat(64)},{...v,containers:[{...v.containers[0]!,backgroundHover:1.01}]},{...v,containers:[v.containers[0],v.containers[0]]},{...v,containers:[{...v.containers[0]!,private:'x'}]}])expect(resolveP15ElementorContainerHoverTransitions(s,bad).status).toBe('REJECTED');const conflict={...v,containers:[{...v.containers[0]!,backgroundHover:1}]};const s2={...s,nodes:[{...s.nodes[0],backgroundColorHex:'#123456'}]};expect(resolveP15ElementorContainerHoverTransitions(s2,conflict).status).toBe('REJECTED');});});
