import { buildElementorTemplateCandidateArtifact } from './candidate-artifact';
import { buildElementorTemplateCandidateIdentity } from './import-validation-contract';
import { validateP15NeutralExportDocument, type P15NeutralExportDocumentV1 } from './neutral-export-ir';
import { fingerprintP15NeutralExportDocument } from './neutral-export-ir-identity';
import { bindP15NeutralSourceToGeneratedContainers, cloneP15ReadyElementorTemplate, collectP15NeutralContainerNodes } from './responsive-container-binding';
import { generateElementorV3TemplateCandidate } from './v3-template-generator';

export const P15_ELEMENTOR_CONTAINER_OVERLAY_VISUAL_MANIFEST_VERSION='p15-elementor-container-overlay-visual-manifest-v1' as const;
export const P15_ELEMENTOR_CONTAINER_OVERLAY_BLEND_MODES=['','multiply','screen','overlay','darken','lighten','color-dodge','saturation','color','luminosity'] as const;
export interface P15ContainerCssFilterV1{blur?:number;brightness?:number;contrast?:number;saturate?:number;hue?:number;}
export interface P15ContainerOverlayVisualEntryV1{sourceNodeId:string;blendMode?:typeof P15_ELEMENTOR_CONTAINER_OVERLAY_BLEND_MODES[number];normal?:P15ContainerCssFilterV1;hover?:P15ContainerCssFilterV1;}
const rec=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const finite=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
const filter=(v:unknown):v is P15ContainerCssFilterV1=>rec(v)&&Object.keys(v).every(k=>['blur','brightness','contrast','saturate','hue'].includes(k))&&(v.blur===undefined||finite(v.blur,0,10))&&(v.brightness===undefined||finite(v.brightness,0,200))&&(v.contrast===undefined||finite(v.contrast,0,200))&&(v.saturate===undefined||finite(v.saturate,0,200))&&(v.hue===undefined||finite(v.hue,0,360));
function patchFilter(node:Record<string,unknown>,prefix:string,value:P15ContainerCssFilterV1){for(const [k,v] of Object.entries(value)){const key=`${prefix}_${k}`;if(Object.prototype.hasOwnProperty.call(node,key))throw new Error('CONFLICT');node[key]={size:v,unit:k==='blur'?'px':k==='hue'?'deg':'%'};}}
export function resolveP15ElementorContainerOverlayVisuals(sourceValue:unknown,manifestValue:unknown):any{const validation=validateP15NeutralExportDocument(sourceValue);if(!validation.valid)return{status:'BLOCKED',issues:['SOURCE_INVALID']};const source=sourceValue as P15NeutralExportDocumentV1;const fingerprint=fingerprintP15NeutralExportDocument(source);const gen=generateElementorV3TemplateCandidate(source);if(!gen.candidate)return{status:'BLOCKED',issues:['BASE_NOT_READY']};if(!rec(manifestValue)||manifestValue.manifestVersion!==P15_ELEMENTOR_CONTAINER_OVERLAY_VISUAL_MANIFEST_VERSION||!Array.isArray(manifestValue.containers))return{status:'REJECTED',issues:['MANIFEST_INVALID']};const ids=new Set(collectP15NeutralContainerNodes(source).keys());const target=cloneP15ReadyElementorTemplate(gen.candidate);const binding=bindP15NeutralSourceToGeneratedContainers(source,target);const base=buildElementorTemplateCandidateIdentity(gen.candidate).digest;if(binding.issues.length)return{status:'REJECTED',issues:['BINDING_MISMATCH']};const seen=new Set<string>();try{for(const e of manifestValue.containers){if(!rec(e)||typeof e.sourceNodeId!=='string'||!ids.has(e.sourceNodeId)||seen.has(e.sourceNodeId)||(!e.normal&&!e.hover&&e.blendMode===undefined)||(!filter(e.normal)&&e.normal!==undefined)||(!filter(e.hover)&&e.hover!==undefined)||e.blendMode!==undefined&&!P15_ELEMENTOR_CONTAINER_OVERLAY_BLEND_MODES.includes(e.blendMode as typeof P15_ELEMENTOR_CONTAINER_OVERLAY_BLEND_MODES[number]))return{status:'REJECTED',issues:['ENTRY_INVALID']};seen.add(e.sourceNodeId);const node=binding.containers.get(e.sourceNodeId);if(!node||!rec(node.settings))return{status:'REJECTED',issues:['BINDING_MISMATCH']};if(e.blendMode!==undefined){if(Object.prototype.hasOwnProperty.call(node.settings,'overlay_blend_mode'))throw Error('CONFLICT');node.settings.overlay_blend_mode=e.blendMode;}if(e.normal)patchFilter(node.settings,'css_filters',e.normal);if(e.hover)patchFilter(node.settings,'css_filters_hover',e.hover);}}catch{return{status:'REJECTED',issues:['CONFLICT']};}const candidate=buildElementorTemplateCandidateArtifact(target);if(candidate.status!=='READY_FOR_TARGET_IMPORT_VALIDATION'||!candidate.validation.valid)return{status:'REJECTED',issues:['TARGET_INVALID']};return{schemaVersion:1,manifestVersion:P15_ELEMENTOR_CONTAINER_OVERLAY_VISUAL_MANIFEST_VERSION,status:'RESOLVED',sourceIrFingerprint:fingerprint,baseCandidateIdentityDigest:base,resolvedCandidateIdentityDigest:buildElementorTemplateCandidateIdentity(candidate).digest,resolvedEntries:manifestValue.containers,issues:[],template:target,candidate,responsiveInferencePerformed:false,figmaMutation:false,networkAccess:false,targetCompatibilityClaim:false,productionAcceptance:false,downloadEnabled:false};}
export function serializeP15ElementorContainerOverlayVisualSummary(value:any){if(!value||value.status!=='RESOLVED')throw Error('Invalid summary');return JSON.stringify({schemaVersion:1,manifestVersion:P15_ELEMENTOR_CONTAINER_OVERLAY_VISUAL_MANIFEST_VERSION,status:value.status,sourceIrFingerprint:value.sourceIrFingerprint,baseCandidateIdentityDigest:value.baseCandidateIdentityDigest,resolvedCandidateIdentityDigest:value.resolvedCandidateIdentityDigest,resolvedEntries:value.resolvedEntries,issues:value.issues,responsiveInferencePerformed:false,figmaMutation:false,networkAccess:false,targetCompatibilityClaim:false,productionAcceptance:false,downloadEnabled:false},null,2)+'\n';}
