from pathlib import Path

TX = Path('src/core/p14-retained-duplicate-transaction.ts')
README = Path('README.md')


def replace_exact(old: str, new: str, count: int = 1):
    text = TX.read_text()
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'{TX}: expected {count} copies of anchor, found {actual}')
    TX.write_text(text.replace(old, new, count))


def replace_readme_exact(old: str, new: str, count: int = 1):
    text = README.read_text()
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'{README}: expected {count} copies of anchor, found {actual}')
    README.write_text(text.replace(old, new, count))

replace_exact(
    """import {\n  validateP14CandidateHandleEvidence,\n  validateP14RecipeExecutionResultEvidence,\n  validateP14RetentionEvidence,\n} from './p14-adapter-evidence';\n""",
    """import {\n  validateP14CandidateHandleEvidence,\n  validateP14RecipeExecutionResultEvidence,\n  validateP14RetentionEvidence,\n} from './p14-adapter-evidence';\nimport {\n  assessP14CancellationCheck,\n  boundedP14CancellationFailureDetail,\n} from './p14-cancellation-check';\n""",
)

replace_exact(
    """async function cancelled(check?: () => boolean | Promise<boolean>): Promise<boolean> {\n  return check ? Boolean(await check()) : false;\n}\n\n""",
    "",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'CANCELLED',\n      terminalState: 'CANCELLED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError('P14_CANCELLED', 'pre-clone', 'Preparation was cancelled before cloning.')],\n      events: [...events, event(now, 'CANCELLED', 'cancelled before clone')],\n    });\n  }\n""",
    """  const preCloneCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preCloneCancellation.failure) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'BLOCKED',\n      terminalState: 'BLOCKED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-clone-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before cloning', preCloneCancellation.failure),\n        'Fix the cancellation/control callback and retry the current preparation plan.',\n      )],\n      events: [...events, event(now, 'BLOCKED', 'pre-clone cancellation check failed')],\n    });\n  }\n  if (preCloneCancellation.cancelled) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'CANCELLED',\n      terminalState: 'CANCELLED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError('P14_CANCELLED', 'pre-clone', 'Preparation was cancelled before cloning.')],\n      events: [...events, event(now, 'CANCELLED', 'cancelled before clone')],\n    });\n  }\n""",
)

replace_exact(
    """    if (await cancelled(input.shouldCancel)) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError('P14_CANCELLED', 'transform', 'Preparation was cancelled between recipes.'),\n        discardError,\n        rejectedState: 'CANCELLED',\n      });\n    }\n""",
    """    const transformCancellation = await assessP14CancellationCheck(input.shouldCancel);\n    if (transformCancellation.failure) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError(\n          'P14_INTERNAL_INVARIANT_FAILED',\n          'transform-cancellation-check',\n          boundedP14CancellationFailureDetail('Cancellation check failed between recipe checkpoints', transformCancellation.failure),\n          'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n        ),\n        discardError,\n      });\n    }\n    if (transformCancellation.cancelled) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError('P14_CANCELLED', 'transform', 'Preparation was cancelled between recipes.'),\n        discardError,\n        rejectedState: 'CANCELLED',\n      });\n    }\n""",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-validation', 'Preparation was cancelled before validation.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n  }\n""",
    """  const preValidationCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preValidationCancellation.failure) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-validation-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before validation', preValidationCancellation.failure),\n        'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n      ),\n      discardError,\n    });\n  }\n  if (preValidationCancellation.cancelled) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-validation', 'Preparation was cancelled before validation.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n  }\n""",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-finalize', 'Preparation was cancelled before finalization.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n    return { ...result, validation, rescore };\n  }\n""",
    """  const preFinalizeCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preFinalizeCancellation.failure) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-finalize-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before finalization', preFinalizeCancellation.failure),\n        'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n      ),\n      discardError,\n    });\n    return { ...result, validation, rescore };\n  }\n  if (preFinalizeCancellation.cancelled) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-finalize', 'Preparation was cancelled before finalization.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n    return { ...result, validation, rescore };\n  }\n""",
)

replace_readme_exact(
    "- `docs/COMMERCIAL_EXPANSION_PLAN.md` — P13-P26 commercial roadmap;",
    "- `docs/COMMERCIAL_EXPANSION_PLAN.md` — retained P13-P26 commercial implementation roadmap; P27 final production-release gate is tracked by #182;",
)

replace_readme_exact(
    """**Open PR/MR:** `0 baseline before this focused sync branch; expected 0 again after merge`.\n\nOpen issues:\n\n- `#84` — P12 final validation: active manual/publisher/runtime exit gate.\n- `#119` — P13-P26 commercial/multi-target expansion owner; planning/preflight complete, runtime implementation blocked by #84 internal exit.\n""",
    """**Open PR/MR:** see the repository's current pull-request list; this README intentionally does not hardcode a count.\n\nOpen roadmap / acceptance issues:\n\n- `#84` — P12 retained final validation/release-exit truth; remaining live runtime/publisher/2FA evidence is intentionally deferred to the final release sequence.\n- `#119` — P13-P27 commercial/multi-target roadmap owner; P13-P26 implementation/testing may proceed before final production release.\n- `#159` — P13 real-plugin Build-Ready runtime/parity evidence and internal runtime-acceptance dependency.\n- `#182` — P27 final production-release gate coordinating the remaining external/manual release evidence and final release decision.\n""",
)

replace_readme_exact(
    """The P13-P26 planning/preflight sequence is now retained end-to-end. P13-P16 froze the initial readiness/duplicate/Elementor/Gutenberg contracts, P17-P20 froze universal web/framework/assets/round-trip QA, and PRs #141-#146 froze P21-P26 handoff, estimation, agency/project state, dynamic data, commercial entitlements and optional AI. The final P26 planning merge is `451656e7907803f75a715d7cbd93390a3931bea8`. This planning completion grants **no P13-P26 runtime acceptance credit**: every phase remains at `0%` implementation until #84 internal exit genuinely passes.\n""",
    """The retained P13-P26 planning/preflight sequence remains the implementation contract. Since that freeze, P13 Build-Ready Score/Responsive Risk core plus plugin/CLI integration and real-source calibration have been implemented; real-plugin runtime/parity acceptance remains open in #159. P14 target-neutral retained-duplicate preparation is under active pure-core hardening with production recipe authority and real Figma mutation exposure intentionally unwired. P15-P26 remain preflight-frozen and implementation-not-started. Under roadmap #119, those implementation/test slices are no longer blocked by #84; production acceptance/release remains a separate P27/#182 decision and #84 retains the P12 release-exit truth.\n""",
)

old_rows = """| P13 Build-Ready Score 2.0 + Responsive Risk | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | #84 internal P12 exit first; then focused implementation issue |\n| P14 Target-Ready Duplicate + Guided Prepare | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | P13 accepted implementation evidence first |\n| P15 Elementor native export + validation | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | R0+R1 refresh as needed; versioned v3/v4 adapter + real import proof |\n| P16 Gutenberg native export + transfer | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | R0+R1 refresh as needed; native block/pattern/editor validation |\n| P17 HTML/CSS/JS + code-to-design | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Static-first contract retained; JS execution remains separately gated |\n| P18 Framework adapter platform | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Neutral Web IR + versioned adapter/build matrix retained |\n| P19 Assets/fonts/design-system export | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Asset/token provenance and font constraints retained |\n| P20 Round-trip QA + section portability | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Controlled render harness + calibrated QA required in implementation |\n| P21 Handoff/client QA/a11y-SEO advisories | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Build from accepted target outputs; bounded claim rules retained |\n| P22 Complexity / effort estimator | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Transparent effort-unit/calibration contract retained |\n| P23 Agency/project/component bindings | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Stable implemented adapters first; semantic invalidation contract retained |\n| P24 CMS/dynamic/forms/interactions | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Typed data/form/provider mappings retained; production writes remain out of first slice |\n| P25 Free / Pro / Agency packaging | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Capability-based entitlement contract retained; publisher eligibility remains external/account-specific |\n| P26 Optional AI assistance | PREFLIGHT FROZEN / IMPLEMENTATION BLOCKED | 0% | `░░░░░░░░░░` | Non-authoritative AI authority firewall retained; provider/network choice still unselected |\n"""
new_rows = """| P13 Build-Ready Score 2.0 + Responsive Risk | IMPLEMENTATION COMPLETE / RUNTIME ACCEPTANCE PENDING | 100% impl | `██████████` | #159 real-plugin parity/internal runtime acceptance remains; production release is later P27 |\n| P14 Target-Ready Duplicate + Guided Prepare | CORE IMPLEMENTATION IN PROGRESS / RUNTIME UNWIRED | N/A | `──────────` | Continue pure-core fail-closed hardening; production registry remains empty; #159 required before real Figma mutation exposure |\n| P15 Elementor native export + validation | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | R0+R1 refresh as needed; versioned v3/v4 adapter + real import proof |\n| P16 Gutenberg native export + transfer | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | R0+R1 refresh as needed; native block/pattern/editor validation |\n| P17 HTML/CSS/JS + code-to-design | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Static-first contract retained; JS execution remains separately gated |\n| P18 Framework adapter platform | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Neutral Web IR + versioned adapter/build matrix retained |\n| P19 Assets/fonts/design-system export | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Asset/token provenance and font constraints retained |\n| P20 Round-trip QA + section portability | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Controlled render harness + calibrated QA required in implementation |\n| P21 Handoff/client QA/a11y-SEO advisories | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Build from accepted target outputs; bounded claim rules retained |\n| P22 Complexity / effort estimator | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Transparent effort-unit/calibration contract retained |\n| P23 Agency/project/component bindings | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Stable implemented adapters first; semantic invalidation contract retained |\n| P24 CMS/dynamic/forms/interactions | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Typed data/form/provider mappings retained; production writes remain out of first slice |\n| P25 Free / Pro / Agency packaging | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Capability-based entitlement contract retained; publisher eligibility remains external/account-specific |\n| P26 Optional AI assistance | PREFLIGHT FROZEN / IMPLEMENTATION NOT STARTED | 0% | `░░░░░░░░░░` | Non-authoritative AI authority firewall retained; provider/network choice still unselected |\n| P27 Final production release + publisher/runtime evidence | GATE DEFINED / EXECUTION DEFERRED | 0% exec | `░░░░░░░░░░` | Run after implementation/internal-readiness sequence; coordinate retained #84 truth + final live runtime/publisher/2FA evidence |\n"""
replace_readme_exact(old_rows, new_rows)

replace_readme_exact(
    """**Overall active project progress:** `██████████ 100%`\n\nHistorical P0-P7 core remains 100%. P12 is tracked separately at 80%. R0/R1 gate definitions are complete but must be re-executed per applicable adapter. **P13-P26 planning/preflight is complete, while P13-P26 runtime implementation remains 0% and is not implementation-authorized until #84 internal exit.**\n""",
    """**Overall progress is intentionally not collapsed into one synthetic percentage.** Historical P0-P7 core remains 100%; P12 remains 80%; P13 implementation is complete with runtime acceptance pending; P14 core implementation is active and runtime-unwired; P15-P26 implementation is not started; P27 release execution is not started.\n\nR0/R1 gate definitions remain complete but are re-executed where applicable. Implementation completion, real-runtime acceptance and production release are separate evidence states; one does not imply another.\n""",
)

replace_readme_exact(
    """## Current execution order\n\n1. capture fresh exact release #20 Figma Desktop runtime evidence;\n2. capture fresh Publish → Add final details evidence with the generated publishing ID accepted and intended publisher/Community/support/network facts visible;\n3. capture fresh Figma 2FA-enabled account/security evidence;\n4. run the exact release #20 publisher-evidence intake and retain the receipt;\n5. perform the final P12 internal exit review from the receipt + retained screenshots;\n6. close P12 internal exit only on retained evidence;\n7. open focused P13 implementation issue from #119 using `docs/P13_BUILD_READY_SCORE_SPEC.md` as the frozen preflight contract;\n8. refresh R0 before each major external adapter if platform facts materially changed;\n9. execute R1 before implementing/accepting each major adapter;\n10. implement P13-P26 in dependency order with one focused issue/branch/PR per slice; planning/preflight is already retained and must not be confused with implementation acceptance.\n""",
    """## Current execution order\n\n1. continue P14 pure-core implementation/hardening with focused issue/branch/PR slices while real Figma mutation remains unwired;\n2. complete P13 #159 real-plugin runtime/parity acceptance when genuine real-Figma evidence is available; #159 is required before P14 real mutation exposure, not before pure-core development;\n3. refresh R0 before each major external adapter if platform facts materially changed;\n4. execute R1 before implementing/accepting each major adapter;\n5. implement P15-P26 in dependency order with one focused issue/branch/PR per slice, preserving the distinction between implementation, internal readiness and production acceptance;\n6. use P27 #182 as the final production-release sequence only after the implementation/internal-readiness program is ready;\n7. during P27, capture the remaining exact release runtime, Publish final-details and 2FA evidence, run the retained P12 publisher-evidence intake, and perform the genuine #84 release-exit decision;\n8. treat Community submission/review/approval as external to internal production acceptance.\n""",
)
