from pathlib import Path

TX = Path('src/core/p14-retained-duplicate-transaction.ts')


def replace_exact(old: str, new: str, count: int = 1):
    text = TX.read_text()
    actual = text.count(old)
    if actual != count:
        raise SystemExit(f'{TX}: expected {count} copies of anchor, found {actual}')
    TX.write_text(text.replace(old, new, count))

replace_exact(
    """import {\n  validateP14CandidateHandleEvidence,\n  validateP14RecipeExecutionResultEvidence,\n  validateP14RetentionEvidence,\n} from './p14-adapter-evidence';\n""",
    """import {\n  validateP14CandidateHandleEvidence,\n  validateP14RecipeExecutionResultEvidence,\n  validateP14RetentionEvidence,\n} from './p14-adapter-evidence';\nimport {\n  assessP14CancellationCheck,\n  boundedP14CancellationFailureDetail,\n} from './p14-cancellation-check';\n""",
)

replace_exact(
    """async function cancelled(check?: () => boolean | Promise<boolean>): Promise<boolean> {\n  return check ? Boolean(await check()) : false;\n}\n\n""",
    "",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'CANCELLED',\n      terminalState: 'CANCELLED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError('P14_CANCELLED', 'pre-clone', 'Preparation was cancelled before cloning.')],\n      events: [...events, event(now, 'CANCELLED', 'cancelled before clone')],\n    });\n  }\n""",
    """  const preCloneCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preCloneCancellation.failure) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'BLOCKED',\n      terminalState: 'BLOCKED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-clone-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before cloning', preCloneCancellation.failure),\n        'Fix the cancellation/control callback and retry the current preparation plan.',\n      )],\n      events: [...events, event(now, 'BLOCKED', 'pre-clone cancellation check failed')],\n    });\n  }\n  if (preCloneCancellation.cancelled) {\n    return baseReceipt({\n      plan,\n      transactionId: input.transactionId,\n      status: 'CANCELLED',\n      terminalState: 'CANCELLED',\n      beforeFingerprint,\n      afterFingerprint: beforeFingerprint,\n      errors: [receiptError('P14_CANCELLED', 'pre-clone', 'Preparation was cancelled before cloning.')],\n      events: [...events, event(now, 'CANCELLED', 'cancelled before clone')],\n    });\n  }\n""",
)

replace_exact(
    """    if (await cancelled(input.shouldCancel)) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError('P14_CANCELLED', 'transform', 'Preparation was cancelled between recipes.'),\n        discardError,\n        rejectedState: 'CANCELLED',\n      });\n    }\n""",
    """    const transformCancellation = await assessP14CancellationCheck(input.shouldCancel);\n    if (transformCancellation.failure) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError(\n          'P14_INTERNAL_INVARIANT_FAILED',\n          'transform-cancellation-check',\n          boundedP14CancellationFailureDetail('Cancellation check failed between recipe checkpoints', transformCancellation.failure),\n          'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n        ),\n        discardError,\n      });\n    }\n    if (transformCancellation.cancelled) {\n      const discardError = await discardCandidate(adapter, candidate);\n      return cleanupOutcome({\n        plan,\n        transactionId: input.transactionId,\n        beforeFingerprint,\n        afterFingerprint: unknownFingerprint,\n        candidate,\n        appliedActions,\n        events,\n        now,\n        primaryError: receiptError('P14_CANCELLED', 'transform', 'Preparation was cancelled between recipes.'),\n        discardError,\n        rejectedState: 'CANCELLED',\n      });\n    }\n""",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-validation', 'Preparation was cancelled before validation.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n  }\n""",
    """  const preValidationCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preValidationCancellation.failure) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-validation-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before validation', preValidationCancellation.failure),\n        'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n      ),\n      discardError,\n    });\n  }\n  if (preValidationCancellation.cancelled) {\n    const discardError = await discardCandidate(adapter, candidate);\n    return cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-validation', 'Preparation was cancelled before validation.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n  }\n""",
)

replace_exact(
    """  if (await cancelled(input.shouldCancel)) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-finalize', 'Preparation was cancelled before finalization.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n    return { ...result, validation, rescore };\n  }\n""",
    """  const preFinalizeCancellation = await assessP14CancellationCheck(input.shouldCancel);\n  if (preFinalizeCancellation.failure) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError(\n        'P14_INTERNAL_INVARIANT_FAILED',\n        'pre-finalize-cancellation-check',\n        boundedP14CancellationFailureDetail('Cancellation check failed before finalization', preFinalizeCancellation.failure),\n        'Fix the cancellation/control callback and re-run preparation from a fresh plan.',\n      ),\n      discardError,\n    });\n    return { ...result, validation, rescore };\n  }\n  if (preFinalizeCancellation.cancelled) {\n    const discardError = await discardCandidate(adapter, candidate);\n    const result = cleanupOutcome({\n      plan,\n      transactionId: input.transactionId,\n      beforeFingerprint,\n      afterFingerprint: unknownFingerprint,\n      candidate,\n      appliedActions,\n      events,\n      now,\n      primaryError: receiptError('P14_CANCELLED', 'pre-finalize', 'Preparation was cancelled before finalization.'),\n      discardError,\n      rejectedState: 'CANCELLED',\n    });\n    return { ...result, validation, rescore };\n  }\n""",
)
